#!/usr/bin/env python

import sys

from light_beacon_gui.light_beacon_gui import LightBeaconGui
from rqt_gui.main import Main

plugin = 'light_beacon_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
